### ISSUE TITLE
Add grammar for clojure

### ISSUE THREAD

**Issue by jasonjckn** [emacs-tree-sitter/tree-sitter-langs#143]
Can we get a clojure grammar https://github.com/sogaiu/tree-sitter-clojure added to this project please?

**Comment by sogaiu** [comment]
At this point I'm not sure it's a good idea.

IIUC, due to a (perhaps unintentional) [breaking change in tree-sitter](https://github.com/tree-sitter/tree-sitter/pull/1157), elisp-tree-sitter / tree-sitter-langs doesn't work with the 0.20.x series of tree-sitter.  There is [an outstanding issue](https://github.com/tree-sitter/tree-sitter/issues/1336) concerning this, but even if the changes were incorporated into tree-sitter, as I understand it, elisp-tree-sitter / tree-sitter-langs itself would also need to be updated to use the changes.

Both the aforementiond issue and elisp-tree-sitter / tree-sitter-langs are authored by the same indiviual AFAICT and neither has seen much activity recently.

I've kept tree-sitter-clojure at the 0.19.y series of tree-sitter because I didn't want to adversely impact elisp-tree-sitter (though I'm only aware one person -- @ag91 -- who made use of both).  I would like to eventually be moving tree-sitter-clojure on from the 0.19.y series.  Assuming the situation described above concerning tree-sitter and elisp-tree-sitter / tree-sitter-langs is not likely to change soon, if existing users of tree-sitter-clojure transition to using Emacs 29's tree-sitter integration I think that makes things less problematic maintenance- and breakage-wise.

Along those lines I think having addititional new users of tree-sitter-clojure via elisp-tree-sitter / tree-sitter-langs is not so desirable at this time.

**Comment by sogaiu** [comment]
Looks like it got added anyway: https://github.com/emacs-tree-sitter/tree-sitter-langs/commit/c4dbcb2b89cf825f18016fb973f50489741ca347

So perhaps this issue can be closed?

**Comment by jasonjckn** [comment]
yes we can close this 🥳
