### ISSUE TITLE
Automatically build tree-sitter-langs from source instead of downloading binaries on arm64 (m1) machines

### ISSUE THREAD

**Issue by shaunsingh** [emacs-tree-sitter/tree-sitter-langs#36]
Hi, loving the idea (and treesitter on my x86 machine) so far. If emacs is running on an arm64 machine, would it be possible to have tree-sitter-langs automatically download the source and compile the parsers, insetad of download the binary and failing with no warning?

**Comment by ubolonton** [comment]
Yes, all the low-level building blocks are already in `tree-sitter-langs-build.el`, but they currently assume a cloned git repository. Some additional code to handle source downloading is needed.

**Comment by Mic92** [comment]
In the meantime I think you can also use nix to download the grammars: https://github.com/Mic92/dotfiles/blob/3c99578315d30cd23ed2d4f7d8dbf560daaf2820/nixpkgs-config/modules/emacs/default.nix#L79

If that is not your cup of cake you can still configure emacs-tree-sitter to load grammars from a custom directory: https://github.com/Mic92/dotfiles/blob/3c99578315d30cd23ed2d4f7d8dbf560daaf2820/home/.doom.d/config.el#L187

**Comment by shaunsingh** [comment]
I don't actually use nix on my m1/darwin machine, but I have compiled the parsers locally and am already loading them from a custom directory! This issue was just raised in the doom emacs server so I thought it would be nice to openan issue here

**Comment by morphykuffour** [comment]
I have the tsc-dyn.aarch64-apple-darwin.dylib file downloaded how do I load the dynamic library in order to get emacs to (require 'tree-sitter). I have added the core, lisp, and langs to the load path. I am still getting the tsc-dyn error when I try to evaluate the load the tree-sitter plugin. See images below.

![Screen Shot 2022-01-23 at 12 51 59 PM](https://user-images.githubusercontent.com/23323356/150691288-b55771f3-01dd-4b7b-9ff8-1f6271484c8d.png)

![Screen Shot 2022-01-23 at 12 52 53 PM](https://user-images.githubusercontent.com/23323356/150691321-e4544031-c062-4446-940b-dc171af9a9cb.png)

**Comment by ubolonton** [comment]
You will need to rename it to `tsc-dyn.dylib` and put it into `core/`.

**Comment by morphykuffour** [comment]
yeah did not work. I renamed the file and I put in the core directory of the elisp-tree-sitter git repo cloned on my manchine. 
![Screen Shot 2022-01-26 at 7 37 33 PM](https://user-images.githubusercontent.com/23323356/151270183-02d4493c-2f4a-4b2b-8c53-51bcababe53f.png)

**Comment by ubolonton** [comment]
There’s not enough information to troubleshoot currently. Please describe what happened in more details, e.g. errors/tracebacks. Minimal reproduction steps would be helpful.
